
project_id = "jommzzooscybfjdwuftf"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
port = 54327
uri = "http://localhost:54321/auth/v1"

[storage]
port = 54328

[realtime]
port = 54329

[functions]
port = 54330
