// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jommzzooscybfjdwuftf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbW16em9vc2N5YmZqZHd1ZnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjYzODcsImV4cCI6MjA1NzgwMjM4N30.aPDXiGZXUp-diDXKVgMnif_MPW3Xm8DcP__5Kb98Rkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);